### CREATE USER
POST http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTU4NDI2MywiZXhwIjoxNzQ1NjcwNjYzfQ.UnYkDhQrAX-96WhGjLMiFg6VRhefhhQCT6COb9Vtgig
{
  "email": "loback.filipe@exemplo.com",
  "name": "filipe siqueira",
  "password": "senha123",
  "status": true,
  "type_user": "admin"
}

### FIND BY ID
GET http://localhost:3000/user/3bbe3736-cbe0-4b01-868f-c8d5661397ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTU4NDI2MywiZXhwIjoxNzQ1NjcwNjYzfQ.UnYkDhQrAX-96WhGjLMiFg6VRhefhhQCT6COb9Vtgig

### FIND ALL USER
GET  http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTUxOTI4OCwiZXhwIjoxNzQ1NjA1Njg4fQ.Jg1b5L9DkdGBv25Qi_OMMHljcwnY91VnCsLWHCjNZhQ

### UPDATE USER
PATCH http://localhost:3000/user/aa1fac24-6f51-4e36-a2d0-b08de6bb12cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTU4NDI2MywiZXhwIjoxNzQ1NjcwNjYzfQ.UnYkDhQrAX-96WhGjLMiFg6VRhefhhQCT6COb9Vtgig
Content-Type: application/json

{
  "email": "ingredi.ramos@exemplo.com",
  "name": "Ingredi Ramos",
  "password": "123muda",
  "status": false,
  "type_user": "admin"
}

### DELETE USER
DELETE http://localhost:3000/user/000b5d3b-e567-4a25-8f1f-2d725d06a26d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTU4NDI2MywiZXhwIjoxNzQ1NjcwNjYzfQ.UnYkDhQrAX-96WhGjLMiFg6VRhefhhQCT6COb9Vtgig