### CREATE USER
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "filipe.siqueira@exemplo.com",
  "name": "filipe siqueira",
  "password": "senha123",
  "status": true,
  "type_user": "admin"
}

### FIND BY ID
GET http://localhost:3000/user/3bbe3736-cbe0-4b01-868f-c8d5661397ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTUxOTI4OCwiZXhwIjoxNzQ1NjA1Njg4fQ.Jg1b5L9DkdGBv25Qi_OMMHljcwnY91VnCsLWHCjNZhQ


### FIND ALL USER
GET  http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTUxOTI4OCwiZXhwIjoxNzQ1NjA1Njg4fQ.Jg1b5L9DkdGBv25Qi_OMMHljcwnY91VnCsLWHCjNZhQ

### UPDATE USER
PATCH http://localhost:3000/user/000b5d3b-e567-4a25-8f1f-2d725d06a26d
Content-Type: application/json
Authorization: Bearer

{
  "email": "filipe.loback@exemplo.com",
  "name": "filipe loback",
  "password": "senha123",
  "status": true,
  "type_user": "admin",
}

### DELETE USER
DELETE http://localhost:3000/user/29c91523-35d3-49bc-8eb7-7776f13d4642
Authorization: Bearer
