## CREATE QRCODE qrcode
POST http://localhost:3000/qrcode/generate
Content-Type: application/json
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTY3OTUzNiwiZXhwIjoxNzQ1NzY1OTM2fQ.KUOHYYdntWMcKLAnSAwjfl27xWAehSQ90iiJykKRXbU

{
  "link_add": "https://wa.me/5599999999999?text=Olá%20quero%20saber%20mais!",
  "number_fone": 5521971211060
}


## DELETE MODULE
DELETE http://localhost:3000/qrcode/0d9dbd4b-238a-4c77-bb98-5484e7a0431b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTY3MjM3NiwiZXhwIjoxNzQ1NzU4Nzc2fQ.9s7xVRURL_Ya3VS8yI_UPZkdSPbHe3Ezyq9B9ncOYGY
